### ISSUE TITLE
Kit still coming?

### ISSUE THREAD

**Issue by 3DTOPO** [ThingEngineer/ReactorForge#2]
It looks like no changes have been pushed in 2 years. Just wondering if this project was still being developed and if kits where still going to be made available?

**Comment by ThingEngineer** [comment]
Hey, despite some delay yes this project is still very much alive. I am working on getting the current version of code and schematics cleaned up and ready for release!

You can now support [ReactorForge on Patreon](http://www.patreon.com/ReactorForge), but you definitely don't have to!
