### ISSUE TITLE
Repository uses arduino topic but is in no way an Arduino project

### ISSUE THREAD

**Issue by per1234** [ThingEngineer/ReactorForge#3]
The code is not compatible with the Arduino IDE.

The hardware does not use an Arduino board.

Therefore the use of the `arduino` topic is not appropriate. Please remove it from this repository.

**Comment by ThingEngineer** [comment]
You are correct. At one point I had some parts of this project coded in Arduino and was planing on moving more to the platform but opted not to. I'll update the topics, thanks for the heads up!
